import { test, expect } from '@playwright/test';
import { DataMapPage } from '../../utils/datamap-page';

test.describe('Core Navigation - Minimal Fixtures', { tag: '@fast' }, () => {
    let datamap: DataMapPage;

    test.beforeEach(async ({ page }, testInfo) => {
        datamap = new DataMapPage(page);

        // Use minimal fixture generated by Python tests
        await datamap.goto('minimal_basic.html');
        await datamap.waitForReady(testInfo);
    });

    test('canvas is visible after load', async ({ page }) => {
        const canvas = datamap.getCanvas();
        await expect(canvas).toBeVisible();
    });

    test('canvas has valid dimensions', async ({ page }) => {
        const size = await datamap.getCanvasSize();
        expect(size.width).toBeGreaterThan(0);
        expect(size.height).toBeGreaterThan(0);
    });

    test('initial state renders correctly', async ({ page }) => {
        await datamap.expectCanvasScreenshot('minimal-basic-initial-state.png');
    });

    test('zoom in functionality', async ({ page }, testInfo) => {
        if (testInfo.project.name === 'mobile-safari') {
            test.skip();
            return;
        }

        // Zoom in (negative delta)
        await datamap.zoom(-100);

        await datamap.expectCanvasScreenshot('minimal-basic-after-zoom-in.png');
    });

    test('zoom out functionality', async ({ page }, testInfo) => {
        if (testInfo.project.name === 'mobile-safari') {
            test.skip();
            return;
        }

        // Zoom out (positive delta)
        await datamap.zoom(100);

        await datamap.expectCanvasScreenshot('minimal-basic-after-zoom-out.png');
    });

    test('pan functionality', async ({ page }, testInfo) => {
        const size = await datamap.getCanvasSize();
        const startX = size.width / 2;
        const startY = size.height / 2;
        const endX = startX + 100;
        const endY = startY;

        await datamap.pan(startX, startY, endX, endY);

        await datamap.expectCanvasScreenshot('minimal-basic-after-pan.png');
    });

    test('combined zoom and pan', async ({ page }, testInfo) => {
        if (testInfo.project.name === 'mobile-safari') {
            test.skip();
            return;
        }

        // First zoom in
        await datamap.zoom(-100);

        // Then pan
        const size = await datamap.getCanvasSize();
        await datamap.pan(size.width / 2, size.height / 2, size.width / 2 + 50, size.height / 2 + 50);

        await datamap.expectCanvasScreenshot('minimal-basic-zoom-and-pan.png');
    });
});
