import { test, expect } from '@playwright/test';
import { DataMapPage } from '../../utils/datamap-page';

test.describe('Search Functionality - Minimal Fixtures', { tag: '@fast' }, () => {
    let datamap: DataMapPage;

    test.beforeEach(async ({ page }, testInfo) => {
        datamap = new DataMapPage(page);

        // Use minimal fixture generated by Python tests
        await datamap.goto('minimal_search.html');
        await datamap.waitForReady(testInfo);
    });

    test('search input exists and is visible', async ({ page }) => {
        const hasSearch = await datamap.hasSearch();
        expect(hasSearch).toBe(true);

        const searchInput = datamap.getSearchInput();
        await expect(searchInput).toBeVisible();
    });

    test('search input accepts text', async ({ page }) => {
        const searchInput = datamap.getSearchInput();

        await searchInput.fill('test query');

        const value = await searchInput.inputValue();
        expect(value).toBe('test query');
    });

    test('search highlights matching points', async ({ page }) => {
        // Our fixture has documents with keywords: neural, learning, vision, language, data
        await datamap.search('neural');

        // Take screenshot to verify search highlighting
        await datamap.expectCanvasScreenshot('minimal-search-neural.png');
    });

    test('search with no matches shows empty state', async ({ page }) => {
        // Search for something that doesn't exist
        await datamap.search('xyznonexistent123');

        await datamap.expectCanvasScreenshot('minimal-search-no-matches.png');
    });

    test('clear search restores all points', async ({ page }) => {
        // First search for something
        await datamap.search('vision');
        await page.waitForTimeout(300);

        // Then clear
        await datamap.clearSearch();

        await datamap.expectCanvasScreenshot('minimal-search-after-clear.png');
    });

    test('search is case insensitive', async ({ page }) => {
        // Search with different cases
        await datamap.search('NEURAL');
        const screenshot1 = await datamap.getCanvas().screenshot();

        await datamap.clearSearch();
        await datamap.search('neural');
        const screenshot2 = await datamap.getCanvas().screenshot();

        // Screenshots should be similar (same search results)
        // We're just verifying both searches work without error
        expect(screenshot1).toBeDefined();
        expect(screenshot2).toBeDefined();
    });

    test('multiple search terms narrow results', async ({ page }) => {
        // Search for one term
        await datamap.search('learning');
        await datamap.expectCanvasScreenshot('minimal-search-learning.png');

        // Search for a more specific term
        await datamap.clearSearch();
        await datamap.search('neural learning');
        await datamap.expectCanvasScreenshot('minimal-search-neural-learning.png');
    });
});
