import { test, expect } from '@playwright/test';
import { DataMapPage } from '../../utils/datamap-page';

test.describe('On-Click Action Functionality', { tag: '@fast' }, () => {
    let datamap: DataMapPage;

    test.beforeEach(async ({ page }, testInfo) => {
        datamap = new DataMapPage(page);

        // Use minimal fixture generated by Python tests
        await datamap.goto('minimal_onclick.html');
        await datamap.waitForReady(testInfo);
    });

    test('click on canvas initializes click tracking', async ({ page }) => {
        // Our fixture sets window.clickCount on click
        // First verify the variable doesn't exist yet
        const initialCount = await page.evaluate(() => (window as any).clickCount);
        expect(initialCount).toBeUndefined();
    });

    test('click on point triggers on_click action', async ({ page }) => {
        const size = await datamap.getCanvasSize();
        const centerX = size.width / 2;
        const centerY = size.height / 2;

        // Click around the center to find a point
        // Our fixture has on_click that sets window.clickCount
        let clicked = false;

        for (let dx = -75; dx <= 75 && !clicked; dx += 25) {
            for (let dy = -75; dy <= 75 && !clicked; dy += 25) {
                await datamap.clickAt(centerX + dx, centerY + dy);
                await page.waitForTimeout(100);

                const clickCount = await page.evaluate(() => (window as any).clickCount);
                if (clickCount && clickCount > 0) {
                    clicked = true;
                }
            }
        }

        // Verify at least one click was registered
        const finalCount = await page.evaluate(() => (window as any).clickCount);
        expect(finalCount).toBeGreaterThan(0);
    });

    test('on_click receives correct point data', async ({ page }) => {
        const size = await datamap.getCanvasSize();
        const centerX = size.width / 2;
        const centerY = size.height / 2;

        // Click around to find a point
        for (let dx = -75; dx <= 75; dx += 25) {
            for (let dy = -75; dy <= 75; dy += 25) {
                await datamap.clickAt(centerX + dx, centerY + dy);
                await page.waitForTimeout(100);

                const lastClicked = await page.evaluate(() => (window as any).lastClickedPoint);
                if (lastClicked) {
                    // Our fixture hover_text contains point info
                    expect(typeof lastClicked).toBe('string');
                    return;
                }
            }
        }

        // If we get here, we couldn't find a point - that's okay for this synthetic data
        test.skip();
    });

    test('multiple clicks increment counter', async ({ page }) => {
        const size = await datamap.getCanvasSize();
        const centerX = size.width / 2;
        const centerY = size.height / 2;

        // Find a point position that works
        let pointX = centerX;
        let pointY = centerY;
        let foundPoint = false;

        for (let dx = -75; dx <= 75 && !foundPoint; dx += 25) {
            for (let dy = -75; dy <= 75 && !foundPoint; dy += 25) {
                await datamap.clickAt(centerX + dx, centerY + dy);
                await page.waitForTimeout(100);

                const clickCount = await page.evaluate(() => (window as any).clickCount);
                if (clickCount && clickCount > 0) {
                    pointX = centerX + dx;
                    pointY = centerY + dy;
                    foundPoint = true;
                }
            }
        }

        if (!foundPoint) {
            test.skip();
            return;
        }

        // Get current count
        const initialCount = await page.evaluate(() => (window as any).clickCount) || 0;

        // Click the same point multiple times
        await datamap.clickAt(pointX, pointY);
        await page.waitForTimeout(100);
        await datamap.clickAt(pointX, pointY);
        await page.waitForTimeout(100);

        const finalCount = await page.evaluate(() => (window as any).clickCount);
        expect(finalCount).toBeGreaterThan(initialCount);
    });
});
